[package]
name = "borsh_boxed"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
borsh = { workspace = true }

[dev-dependencies]
borsh = { workspace = true }
